- hosts: "{{ target_hosts | default('localhost') }}"

  vars_files:
    - ../ansible/roles/ec2/vars/aws_creds.yml
  vars:
    my_subnets: []
    bigip_server: 10.1.1.245
    bigip_user: admin
    bigip_password: admin
    bigip_validate_certs: no
    bigip_policy_name: foo2
    bigip_rule_name: rule
#    bigip_fw_rule_src_addr: 1.2.3.4
    bigip_fw_rule_dest_addr: 8.8.8.8
    bigip_address_list_name: ansible-address-list
    tag_filter: fooble
    region: ap-southeast-2
    playbook_debug: false

  tasks:
  - name: get subnet facts
    ec2_vpc_subnet_facts:
      region: "{{ region }}"
      filters:
        "tag:type": "{{ tag_filter }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
    register: ec2_subnet_facts
  - debug:
      var=ec2_subnet_facts.subnets
    when: playbook_debug == true
    delegate_to: localhost 
  - name: Create a basic policy named {{ bigip_policy_name }} with some rule stubs
    bigip_firewall_policy:
      name: "{{ bigip_policy_name }}"
      provider:
        password: "{{ bigip_password }}"
        server: "{{ bigip_server }}"
        user: "{{ bigip_user }}"
        validate_certs: "{{ bigip_validate_certs }}"
    delegate_to: localhost
  - name: Create a new individual rule in the {{ bigip_policy_name }} firewall policy
    bigip_firewall_rule:
      name: "{{ item.id }}"
      parent_policy: "{{ bigip_policy_name }}"
      protocol: tcp
      source:
        - address: "{{ item.cidr_block }}"
      destination:
        - address: "{{ bigip_fw_rule_dest_addr }}"
      action: accept
      logging: yes
      provider:
        password: "{{ bigip_password }}"
        server: "{{ bigip_server }}"
        user: "{{ bigip_user }}"
        validate_certs: "{{ bigip_validate_certs }}"
    with_items: "{{ ec2_subnet_facts.subnets }}"
    delegate_to: localhost
  - name: create a dictionary of subnets
    set_fact:
      my_subnets: "{{ my_subnets + [item.cidr_block] }}"
    with_items: "{{ ec2_subnet_facts.subnets }}"
  - debug: 
      var=my_subnets
    when: playbook_debug == true
  - name: Create an address list
    bigip_firewall_address_list:
      name: "{{ bigip_address_list_name }}"
      addresses: "{{ my_subnets }}"
      provider:
        password: "{{ bigip_password }}"
        server: "{{ bigip_server }}"
        validate_certs: "{{ bigip_validate_certs }}"
        user: "{{ bigip_user }}"
      state: present
    delegate_to: localhost
  - name: Create a new addresslist based rule rule in the {{ bigip_policy_name }} firewall policy
    bigip_firewall_rule:
      name: address_list_rule
      parent_policy: "{{ bigip_policy_name }}"
      protocol: tcp
      source:
        - address_list: "{{ bigip_address_list_name }}"
      destination:
        - address: "{{ bigip_fw_rule_dest_addr }}"
      action: accept
      logging: yes
      provider:
        password: "{{ bigip_password }}"
        server: "{{ bigip_server }}"
        user: "{{ bigip_user }}"
        validate_certs: "{{ bigip_validate_certs }}"
    delegate_to: localhost
